plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.14'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'checkstyle'
    id 'eclipse'
    id 'idea'
    id 'jacoco'
    id 'pmd'
}

group = 'com.captechconsulting.alfred'
version = '0.1.0'
description = ''

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    implementation 'org.apache.commons:commons-lang3'
    implementation 'org.apache.hadoop:hadoop-client-api:3.4.2'
    runtimeOnly 'org.apache.hadoop:hadoop-client-runtime:3.4.2'
    implementation 'org.json:json:20250517'

    implementation('org.apache.hive:hive-jdbc:4.2.0') {
        exclude group: 'org.apache.logging.log4j'
        exclude group: 'org.slf4j', module: 'slf4j-log4j12'
        exclude group: 'org.eclipse.jetty'
        exclude group: 'org.eclipse.jetty.aggregate'
        exclude group: 'org.eclipse.jetty.orbit'
    }

    implementation 'org.webjars:bootstrap:5.3.6'

    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'com.vaadin.external.google', module: 'android-json'
    }
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc:3.0.5'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

checkstyle {
    ignoreFailures = true
    checkstyleTest.enabled = false
    configProperties = [ 'checkstyle.header.file': file('config/checkstyle/LICENSE.txt') ]
    showViolations = false
    toolVersion = '10.24.0'
}

javadoc {
    failOnError = false
    options.addBooleanOption('Xdoclint:all,-missing', true)
}

pmd {
    consoleOutput = false
    ignoreFailures = true
    pmdTest.enabled = false
    ruleSetFiles = rootProject.files('config/pmd/ruleset.xml')
    toolVersion = '7.13.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.addAll(['-Xlint:unchecked', '-Xlint:deprecation'])
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

tasks.register('sourcesJar', Jar) {
    dependsOn classes
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives tasks.named('javadocJar')
    archives tasks.named('sourcesJar')
}

wrapper {
    distributionType = Wrapper.DistributionType.ALL
    gradleVersion = '8.14.3'
}
